In [1]:
Books=["DS with Python","BA with Python"]
Books

['DS with Python', 'BA with Python']

In [2]:
2Books=["DS with Python","BA with Python"]
2Books


SyntaxError: invalid syntax (1916705116.py, line 1)

In [3]:
b2ooks=["DS with Python","BA with Python"]
b2ooks

['DS with Python', 'BA with Python']

In [4]:
books+lists=["DS with Python","BA with Python"]
books+lists

SyntaxError: cannot assign to operator (2860965051.py, line 1)

In [5]:
books_lists=["DS with Python","BA with Python"]
books_lists

['DS with Python', 'BA with Python']

In [6]:
_books=["DS with Python","BA with Python"]
_books

['DS with Python', 'BA with Python']

In [7]:
sample_list=[1,13.6,"hi",12,1]
sample_list

[1, 13.6, 'hi', 12, 1]

In [8]:
type(sample_list)

list

In [9]:
sample_list[0]

1

In [10]:
sample_list[-2]

12

In [11]:
sample_list[5]

IndexError: list index out of range

In [12]:
sample_tuple=(1,13,6,"hi",12,1)
sample_tuple

(1, 13, 6, 'hi', 12, 1)

In [13]:
type(sample_tuple)

tuple

In [14]:
sample_tuple=1,13.6,"hi",12,1
type(sample_type)


NameError: name 'sample_type' is not defined

In [15]:
sample_tuple=1,13.6,"hi",12,1
type(sample_tuple)

tuple

In [16]:
sample_tuple[1]

13.6

In [17]:
sample_tuple[-4]

13.6

In [18]:
sample_tuple[-3]

'hi'

In [19]:
sample_type[0]=10

NameError: name 'sample_type' is not defined

In [20]:
sample_set={1,13.6,"hi",12,1,127,25,25,"apple","king","ball"}
sample_set

{1, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [21]:
sample_set[1]

TypeError: 'set' object is not subscriptable

In [22]:
sample_set[0]="hello"

TypeError: 'set' object does not support item assignment

In [24]:
sample_set.add(1000)

In [25]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [27]:
sample_set.remove("hi")

In [28]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'king'}

In [30]:
sample_dict={1:"apple",2:35.4,3:"data",2:"every",6:35.4,2:"hi"}
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4}

In [31]:
sample_dict[2]

'hi'

In [32]:
sample_dict["apple"]

KeyError: 'apple'

In [33]:
sample_dict[7]=100
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 100}

In [34]:
sample_dict[10]="Business"
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 100, 10: 'Business'}

In [35]:
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 100, 10: 'Business'}

In [36]:
import numpy as np

In [37]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [39]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

NameError: name 'sample' is not defined

In [42]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [44]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [1]:
np.zeros(10,dtype=int)

NameError: name 'np' is not defined

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [50]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:

np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.randn(3,2)

array([[0.75417459, 0.18609959],
       [1.06318127, 1.03119551],
       [2.62410026, 0.63385383]])

In [9]:
np.random.randint(34,100)

83

In [10]:
np.random.randint(34,100,50)

array([93, 57, 80, 85, 41, 99, 79, 53, 43, 62, 46, 44, 95, 68, 54, 54, 90,
       59, 63, 84, 89, 77, 59, 87, 78, 52, 88, 82, 58, 65, 88, 85, 80, 94,
       45, 81, 82, 99, 37, 90, 71, 51, 53, 81, 93, 98, 82, 53, 75, 63])

In [12]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
rand_array=np.random.randint(0,100,20)
rand_array


array([45,  1, 98, 67, 25, 40, 26, 77, 21, 74, 54, 39, 67,  1, 81, 64, 79,
        5, 76, 49])

In [14]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [15]:
rand_array.min()

1

In [16]:
rand_array.argmin()

1

In [17]:
rand_array.dtype

dtype('int32')

In [19]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
a=np.random.rand(2,3)
a

array([[0.61434804, 0.92428366, 0.92394018],
       [0.1746078 , 0.06483991, 0.90112334]])

In [23]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
sample_array[3]

13

In [25]:
sample_array[3:7]

array([13, 14, 15, 16])

In [26]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [27]:
sample_array[3]

100

In [28]:
sample_array[3:7]

array([100,  14,  15,  16])

In [29]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [30]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [33]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [34]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [35]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [36]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [37]:
sample_matrix[2][3]

7

In [38]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [39]:
sample_matrix[2]

array([56, 76, 24,  7])

In [40]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [41]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [42]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [43]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [44]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [45]:
np.max(sample_array)

19

In [46]:
np.min(sample_array)

1

In [47]:
np.argmax(sample_array)

18

In [48]:
np.argmin(sample_array)

0

In [49]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [50]:
np.std(sample_array)

5.477225575051661

In [51]:
np.var(sample_array)

30.0

In [52]:
np.mean(sample_array)

10.0

In [53]:
array=np.random.randn(3,4)
array

array([[-0.64163001, -0.53962217,  0.66120875, -0.76058227],
       [-0.27267512,  0.50254063, -0.05198835, -0.47567455],
       [ 0.26386445, -0.59476486, -1.60881036, -0.28794187]])

In [54]:
np.round(array,decimals=3)

array([[-0.642, -0.54 ,  0.661, -0.761],
       [-0.273,  0.503, -0.052, -0.476],
       [ 0.264, -0.595, -1.609, -0.288]])

In [55]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')